spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp
    username: el-3anteel
    password: 1523

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect