spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp
    username: "your mysql username"
    password: "your mysql password"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
